name: PR Check

#    this workflow will run when a PR is opened, synchronized or reopened that is targeting the main or dev branch
on:
    pull_request:
        branches:
            [
                'main',
                dev
            ]

jobs:
    # this job will run on the latest ubuntu runner 
    build-and-test:
        runs-on: ubuntu-latest
        # this step will checkout the repo code so the workflow can access it
        steps:
        - uses: actions/checkout@v3
        
        # Initialize CodeQL for C#
        - name: Initialize CodeQL
          uses: github/codeql-action/init@v2
          with:
            languages: csharp

        # Installs the latest version of .NET SDK that is 8.0.x
        - name: Set up .NET
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 8.0.x
        # this step will download and install all NuGet dependencies for the project
        - name: Restore
          run: dotnet restore
        # this step builds the project in Release mode and skips the restore step, since it was already done in the restore step
        - name: Build
          run: dotnet build --no-restore --configuration Release

        # Run CodeQL analysis
        - name: Run CodeQL
          uses: github/codeql-action/analyze@v2
          
        # this step will run the unit tests for the project and skips the build step, since it was already done in the build step
        - name: Test with code coverage
          run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Threshold=80 /p:ThresholdType=line